### ISSUE TITLE
Crash & not asked for push if not responding to popup when being asked initially.

### ISSUE THREAD

**Issue by tschubotz** [gnosis/safe-ios-legacy#585]
**Describe the bug**
I set up a new Safe, was asked for push access but when to the home screen instead. Reopening the app lead to a crash. Now I'm not getting asked for push access, i.e I cannot make txs.

**To Reproduce**
1. Install app from scratch
2. Set up password
3. Create new Safe
4. When getting the popup for push access, DON'T respond.
5. Tap home button
6. Reopen Safe app
-> App is frozen.
-> After a while, crash.
-> app automatically opens again. I don't get asked for push access again.

**Expected behavior**
- App doesn't crash
- I get asked for push access again if I haven't given it.

**Smartphone (please complete the following information):**
 - Device: iPhone SE
 - iOS Version: 12.2
 - App Version: 1.0.1 (Rinkeby testflight)

**Comment by DmitryBespalov** [comment]
@tschubotz the crash part of this issue was fixed. The issue of not asking for push is a different one.

iOS does not allow opening system push notification alert if the user has declined the push notifications for the app. Nevertheless, we can detect this situation and present an informational alert that explains the issue to the user. This is a separate improvement task, as it was not defined in the first place. I will create a new issue in the product backlog.
