### ISSUE TITLE
WC Deep link support

### ISSUE THREAD

**Issue by sche** [gnosis/safe-ios-legacy#904]
Opening a deeplink should WalletConnect_SessionsList screen.
The logic of opening a wc:// deepling is the same as scanning a qr code from WalletConnect_SessionsList screen.

**Comment by DmitryBespalov** [comment]
// url key in the did finish launching (https://developer.apple.com/documentation/uikit/uiapplicationdelegate/1622921-application)
// https://developer.apple.com/documentation/uikit/uiapplication/launchoptionskey

// https://developer.apple.com/documentation/uikit/uiapplication/1648685-open
// test cases: launching when app killed; when app in bacgkround; when app in foreground?

**Comment by rmeissner** [comment]
This is not necessarily required for the first iteration, since for iOS the WalletConnect library might use a different scheme. If you do this please check with @pedrouid

**Comment by pedrouid** [comment]
For iOS it might be better to listen to different schemes. Ideally we would all use the same deeplinking scheme `wc` like on Android but it's not as simple on iOS because the user doesn't get to choose the Wallet they want to connect. Although you could still register that `wc` scheme, you should also register a universal link for gnosis safe specifically. Then we can list the supported modals on a UI library like Web3Connect.

Here is an example of we tested it with Metamask Mobile and Rainbow Wallet. We listed the "supported wallets" with a universal link. Demo available [here](https://deep-linking--walletconnect-example.netlify.com/)

<img width="368" alt="Screenshot 2019-06-26 13 52 10" src="https://user-images.githubusercontent.com/10136079/60177617-9dc44200-9819-11e9-8df2-cb0786c4542e.png">

We plan to maintain a list of supporting wallets for deep linking on Github similar to that demo on [L172](https://github.com/WalletConnect/walletconnect-example-dapp/blob/3b57b0f8bc5c0b5c57622c27a6055b56fea095ab/src/App.tsx#L172)


```js
const deepLinkSupportedWallets = [
  {
    name: "Metamask",
    color: "orange",
    universalLink: "https://metamask.io",
    deepLink: "metamask:",
    chromeIntent: ""
  },
  {
    name: "Rainbow",
    color: "purple",
    universalLink: "https://rainbow.me",
    deepLink: "rainbow:",
    chromeIntent: ""
  }
];
```

Let me know how we could test this out with Gnosis Safe iOS, happy to assist more.

**Comment by sche** [comment]
@pedrouid universal links are supposed to be unique per app, but they are not so stable as deeplinks. Universal links don't guarantee that the app will handle the request. So for the proper support of universal links we need to implement logic on our site "safe.gnosis.io" to handle cases when app refused to open the link.
Deeplinks, on the other hand, are more stable. We could add support for both "wc:" and "gnosissafe:" deeplinks.
@tschubotz @rmeissner what deeplink name is it better to use for safe? ("safe:", "gnosissafe:")

**Comment by pedrouid** [comment]
Yes, that's true. You would need to handle the use-case where the user clicks on Gnosis Safe wallet but doesn't have it installed by displaying a web page to have them download it. You can have integrate deferred links to allow users to open the session after they download.

The reason we wanted to use universal links instead of deep links is to reduce the number of clicks the user has to click. Whenever you click a deep link, the user is asked "Do you want to open Gnosis Safe". Which becomes cumbersome every time you connect since you also have to approve the session on the Wallet side.

However you can see the logic on the deep linking example on [L282](https://github.com/WalletConnect/walletconnect-example-dapp/blob/3b57b0f8bc5c0b5c57622c27a6055b56fea095ab/src/App.tsx#L282) where we will default to a deep link if the universal link is not present. For example:

```js
  {
    name: "Gnosis Safe",
    color: "blue",
    universalLink: "",
    deepLink: "gnosissafe:",
    chromeIntent: ""
  }
```

**Comment by rmeissner** [comment]
@sche for the deeplink I would use `gnosissafe` or `gs` and we should be able to implement a universalLink handling in the future (maybe we should create a ticket in the `safe` repo for that, to keep track of it)
