### ISSUE TITLE
Wallet.swift line 163

### ISSUE THREAD

**Issue by gnosis-safe-ios-crashlytics** [gnosis/safe-ios-legacy#930]
#### in 

* Number of crashes: 1
* Impacted devices: 1

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/gnosis/ios/apps/io.gnosis.safe/issues/13c885299c7436f4b4b5ec9d460493ec?utm_medium=service_hooks-github&utm_source=issue_impact](https://fabric.io/gnosis/ios/apps/io.gnosis.safe/issues/13c885299c7436f4b4b5ec9d460493ec?utm_medium=service_hooks-github&utm_source=issue_impact)

**Comment by DmitryBespalov** [comment]
It turns out, you can swipe back from the Onboarding_CreationFee screen, and go back to previous screens. If the deployment is already in progress, then the app internally turns into 'readyToUse' state, but the UI is still displaying the pre-deployment screens. The user navigated back to the Confirm Mnemonic (EnterSeed) screen, and then tap 'Next' on that screen led to a crash because of invalid wallet state (readyToUse state prohibits adding owner arbitrarily).

Meanwhile, I have discovered another crash - when going back from the "Onboarding_CreationFeeIntro" screen and then tap "Next" - the app crashes because it tries to add the derived key to the keychain, but the same key already exists.

**Comment by DmitryBespalov** [comment]
Solution: disable swipe back gesture on every controller that sets 'cancel' button or removes 'back' button
